const mongoose = require('mongoose');

/**
 * FaceBiometric Model
 * ====================
 * Stores facial recognition embeddings separately from the User document.
 * 
 * Security:
 * - The `embedding` field uses `select: false` so it is NEVER returned
 *   in normal queries. It must be explicitly requested with `.select('+embedding')`.
 * - One-to-one relationship with User (unique userId).
 * - Biometric data is physically isolated from general user data.
 * 
 * The embedding is a 512-dimensional L2-normalized float array
 * generated by the ArcFace (ResNet-100) model.
 */
const faceBiometricSchema = new mongoose.Schema({
  userId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    required: [true, 'User ID is required'],
    unique: true,
    index: true
  },
  embedding: {
    type: [Number],
    required: [true, 'Face embedding is required'],
    select: false,  // NEVER returned in normal queries
    validate: {
      validator: function (arr) {
        return arr.length === 512;
      },
      message: 'Embedding must be exactly 512 dimensions'
    }
  },
  enrolledAt: {
    type: Date,
    default: Date.now
  }
}, {
  timestamps: true
});

// Do NOT expose embedding in JSON/Object serialization
faceBiometricSchema.methods.toJSON = function () {
  const obj = this.toObject();
  delete obj.embedding;
  return obj;
};

module.exports = mongoose.model('FaceBiometric', faceBiometricSchema);
